### ISSUE TITLE
Seed bug

### ISSUE THREAD

**Issue by andris155** [hankur/RestrictedCreative#57]
RestrictedCreative 2.0c-BUGGY
https://www.youtube.com/watch?v=y6r9QJbZvm8

**Comment by Prunt** [comment]
Couldn't reproduce.

**Comment by andris155** [comment]
I tested. This protection work perfectly without FAWE. This is a FAWE plugin bug?

**Comment by hankur** [comment]
Interesting. Try to add this to FAWE's config.yml:
```YAML
extent:
  allowed-plugins:
  - "RestrictedCreative"
```
